### ISSUE TITLE
limit the 'beacon chain is in inactivity leak' message

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#8064]
```
		2024-03-12 08:19:00.047	
{"@timestamp":"2024-03-11T22:19:00,014","level":"INFO","thread":"TimeTick-1","class":"teku-event-log","message":"Syncing     *** Target slot: 7807295, Head slot: 7772295, Remaining slots: 35000, Connected peers: 95","throwable":""}

2024-03-12 08:18:59.796	
{"@timestamp":"2024-03-11T22:18:59,732","level":"INFO","thread":"beaconchain-async-7","class":"AbstractEpochProcessor","message":"Beacon chain is in inactivity leak","throwable":""}
2024-03-12 08:18:58.543	
{"@timestamp":"2024-03-11T22:18:58,323","level":"INFO","thread":"beaconchain-async-7","class":"AbstractEpochProcessor","message":"Beacon chain is in inactivity leak","throwable":""}
2024-03-12 08:18:56.788	
{"@timestamp":"2024-03-11T22:18:56,640","level":"INFO","thread":"beaconchain-async-7","class":"AbstractEpochProcessor","message":"Beacon chain is in inactivity leak","throwable":""}
2024-03-12 08:18:55.536	
{"@timestamp":"2024-03-11T22:18:55,303","level":"INFO","thread":"beaconchain-async-7","class":"AbstractEpochProcessor","message":"Beacon chain is in inactivity leak","throwable":""}
2024-03-12 08:18:53.531	
{"@timestamp":"2024-03-11T22:18:53,327","level":"INFO","thread":"beaconchain-async-7","class":"AbstractEpochProcessor","message":"Beacon chain is in inactivity leak","throwable":""}
2024-03-12 08:18:52.027	
{"@timestamp":"2024-03-11T22:18:51,899","level":"INFO","thread":"beaconchain-async-7","class":"AbstractEpochProcessor","message":"Beacon chain is in inactivity leak","throwable":""}
2024-03-12 08:18:50.524	
{"@timestamp":"2024-03-11T22:18:50,288","level":"INFO","thread":"beaconchain-async-7","class":"AbstractEpochProcessor","message":"Beacon chain is in inactivity leak","throwable":""}
2024-03-12 08:18:49.021	
{"@timestamp":"2024-03-11T22:18:48,774","level":"INFO","thread":"beaconchain-async-7","class":"AbstractEpochProcessor","message":"Beacon chain is in inactivity leak","throwable":""}
2024-03-12 08:18:48.019	
{"@timestamp":"2024-03-11T22:18:48,014","level":"INFO","thread":"TimeTick-1","class":"teku-event-log","message":"Syncing     *** Target slot: 7807294, Head slot: 7772295, Remaining slots: 34999, Connected peers: 95","throwable":""}
```
It doesnt seem totally consistnet, but we only need this every epoch once...

**Comment by mehdi-aouadi** [comment]
Isn't this a duplicate of https://github.com/Consensys/teku/issues/7329 fixed by https://github.com/Consensys/teku/pull/7788?

**Comment by mehdi-aouadi** [comment]
@rolfyone I'm unable to reproduce this behaviour. In which box did you find these logs?
I checked our goerli nodes and the logs are well throttled as expected (every epoch).
The two boxes where I found the same logs are [goerli-vc-03](https://grafana.o11y.web3factory.consensys.net/d/f24a18e5-d9b8-460b-a6f1-a3007e0c3391/logs-all-teku?orgId=19&var-stack_name=prd-clc-geth-teku-goerli-vc-03&var-ip_addres=&var-level=All&var-job=teku&var-search=Beacon%20chain%20is%20in%20inactivity%20leak&var-network=goerli&var-vnet=All&from=1712919600000&to=1712926799000) and [goerli-vc-01](https://grafana.o11y.web3factory.consensys.net/d/f24a18e5-d9b8-460b-a6f1-a3007e0c3391/logs-all-teku?orgId=19&var-stack_name=prd-clc-besu-teku-goerli-vc-01&var-ip_addres=&var-level=INFO&var-job=teku&var-search=Beacon%20chain%20is%20in%20inactivity%20leak&var-network=goerli&var-vnet=All&from=1712786400000&to=1712959199000). In both the logs happen every epoch only.
Looked at the code too, I didn't see any initialisation issue. Curious to know when did that happen...

**Comment by lucassaldanha** [comment]
It is possible that this was fixed by #7788. If we can't find it happening on any instance after we released #7788 we can probably close this issue.

**Comment by rolfyone** [comment]
IIRC theres an initialization issue where if the epoch (slot?) was unset then it'd continue to spam, we may just need to cater for that case where it's unset...

**Comment by zilm13** [comment]
I saw it when testing PeerDAS, so is not fixed probably with #7788
